[package]
name = "Ferrisouls"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.9.3"
bitflags = "2.13.2"
byteorder = "1.5.0"
cbc = "0.2.1"
cipher = "0.5.2"
encoding_rs = "0.8.42"
flate2 = "1.1.10"
hex-literal = "1.1.0"
libloading = "0.9.0"
md-5 = "0.11.0"
primes = "0.4.0"
roxmltree = "0.21.1"
thiserror = "2.0.21"
zstd = "0.14.0"

[lints.rust]
unused = "allow"
non_snake_case = "allow"
